### ISSUE TITLE
HIGH PRIORITY #20 run HTML thru validator and fix warnings

### ISSUE THREAD

**Issue by mollyfish** [mollyfish/advanced-presentation-AT-MK-wip#20]

**Comment by toalina** [comment]
Working on this.

**Comment by toalina** [comment]
Just ran HTML through validator, only 6 warnings. All were missing headings from <section>, but I'm going to leave them as is. Only 2 of these have actual headings (words) that are outside of the <section> tag, but they also live directly under an <article> tag for that entire section,which I think is more semantically appropriate.

**Comment by mollyfish** [comment]
Sounds great.  I'm about to push my phone menu fix.
