### ISSUE TITLE
Add js

### ISSUE THREAD

**Issue by mollyfish** [mollyfish/advanced-presentation-AT-MK-wip#78]

**Comment by toalina** [comment]
1. PORTFOLIO: 
   Carousel of main image -- Add 1 more for photo sliding 
2. CONTACT:
   Map hover effect -- Hover, then show contact info div
3.   Alert on "Send Message" button -- Warning that message can't be sent
4. TOP NAV: 
5.    Scroll effect on anchor links
6. TEAM: 
7.   Client slider -- Add another client for sliding effect
8. SERVICES:
9.   Sign Up Buttons/Links -- Scroll to CONTACT section

**Comment by mollyfish** [comment]
Split into sub-issues, now obsolete.
